pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
  agent {
    docker {
      image 'snakee/golang-junit:1.21'
      reuseNode true
    }
  }
  environment {
    HOME         = "${WORKSPACE}"
    XDG_CACHE_HOME = "${WORKSPACE}/.cache"
    GOCACHE      = "${WORKSPACE}/.cache/go-build"
    GOPATH       = "${WORKSPACE}/go"
    GOMODCACHE   = "${WORKSPACE}/.cache/gomod"
  }
  steps {
    sh 'mkdir -p "$XDG_CACHE_HOME" "$GOCACHE" "$GOMODCACHE" "$GOPATH/pkg/mod"'
    dir('bugtracker-backend') {
      sh 'go test -v ./...'
    }
  }
}

}
