pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker{
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
             environment {
                HOME = "${WORKSPACE}"
                GOCACHE = "${WORKSPACE}/.cache/go-build"
            }
            steps {
                sh 'mkdir -p "$HOME/.cache" "$GOCACHE"'
                dir('bugtracker-backend'){
                    sh 'go test -v ./...'
                }
            }
        }
    }
}
